### ISSUE TITLE
v1.0.1 :-(

### ISSUE THREAD

**Issue by kawaczek** [byt3bl33d3r/gcat#12]
python gcat.py -list
Traceback (most recent call last):
  File "gcat.py", line 236, in <module>
    gcat.checkBots()
  File "gcat.py", line 99, in checkBots
    msg = msgparser(msg_data)
  File "gcat.py", line 35, in __init__
    self.getPayloads(msg_data)
  File "gcat.py", line 43, in getPayloads
    self.dict = json.loads(payload.get_payload())
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 1 column 2 (char 1)

**Comment by kawaczek** [comment]
I had to delete all messages in your mailbox, and everything is ok :-)
