### ISSUE TITLE
No JSON object could be decoded on "-list"

### ISSUE THREAD

**Issue by Emi1305** [byt3bl33d3r/gcat#17]
I get this error when trying to run "-list"

     Traceback (most recent call last):
      File "Z:\***\gcat\gcat\gcat.py", line 238, in <module>
         gcat.checkBots()
      File "Z:\***\gcat\gcat\gcat.py", line 101, in checkBots
        msg = msgparser(msg_data)
      File "Z:\***\gcat\gcat\gcat.py", line 35, in __init__
        self.getPayloads(msg_data)
      File "Z:\***\gcat\gcat\gcat.py", line 45, in getPayloads
        self.dict = json.loads(payload.get_payload())
      File "E:\Program Files\Python2\lib\json\__init__.py", line 351, in loads
        return cls(encoding=encoding, **kw).decode(s)
      File "E:\Program Files\Python2\lib\json\decoder.py", line 366, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "E:\Program Files\Python2\lib\json\decoder.py", line 384, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

Deleted all messaged and allowed less secure apps but keep getting this error

Thanks

**Comment by git20150901** [comment]
i deleted all message ,and run successfully
