### ISSUE TITLE
gcat on 64bit

### ISSUE THREAD

**Issue by zi-ko** [byt3bl33d3r/gcat#20]
hi @byt3bl33d3r 
i convert implant.py to exe using py2exe and it's work in windows 32 bit 
but when i try to run it on windows 64 bit i have the following error 

C:\lab\gcat>implant.exe
Traceback (most recent call last):
  File "implant.py", line 21, in <module>
    from email.MIMEMultipart import MIMEMultipart
  File "email\__init__.pyc", line 79, in __getattr__
ImportError: No module named multipart

BTW the multipart module installed on my system by 

C:\lab\gcat>pip install --upgrade multipart
You are using pip version 7.0.1, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already up-to-date: multipart in c:\python27\lib\site-packages

**Comment by Nadjorf** [comment]
Try make the executable at windows platform. Is a lot easier and the executable at least runs.

**Comment by ouje** [comment]
Is it possible to use gcat on Windows 10 ?
